name: Insert newly added or modifed xassida in database

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get newly created or updated xassida 
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Run insertion playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: update_db.yml
          directory: .ansible/playbooks/
          key: ${{ secrets.SECRET_SSH_KEY }}
          inventory: |
            [apiservers]
            server1 ansible_host=134.209.180.132 ansible_user=root

          options: |
            --extra-vars xassidas=${{ join(steps.file_changes.outputs.files, ' ') }}
            --user root
            --ssh-extra-args "-o StrictHostKeyChecking=no"
            --verbose
